<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Rate to use for Power factor range' => 'תעריף לשימוש מקדם הספק',
    'Basic rate in Agorot' => 'תעריף בסיס באגורות',
    'End date' => 'תאריך גמר תוקף',
    'Fixed payment for monthly billed clients' => 'תשלום קבוע',
    'Geva' => 'גבע',
    'Geva rate identifier' => 'מזהה תעריף גבע',
    'Name (English)' => 'שם באנגלית',
    'Name (Hebrew)' => 'שם בעברית',
    'Pisga' => 'פסגה',
    'Pisga rate identifier' => 'מזהה תעריף פסגה',
    'Rate identifier' => 'סימול תעריף',
    'Rate {name}' => '{name} תעריף',
    'Season' => 'עונה',
    'Shefel' => 'שפל',
    'Shefel rate identifier' => 'מזהה תעריף שפל',
    'Start date' => 'תאריך תחילת תוקף',
    'This date period has already been taken by {link}' => '{link} תקופת תעריף כבר תפוסה ע"י ',
    'Type' => 'סוג',
    '{attribute} is invalid.' => ' לא תקין {attribute}',
    '{attribute} is required.' => 'שדה חובה {attribute}',
    '{attribute} must be no greater than {date}' => '{date} צריך להיות לא יותר גדול מ{attribute}',
    '{attribute} must be no less than {date}' => '{date} צריך להיות לא יותר קטן מ {attribute}',
];
