<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Import seperatly, Export separatly' => 'ייבוא בנפרד, ייצוא בנפרד',
    'Include VAT' => '',
    'Skip error' => '',
    'There is a {n} or more missing days during the report period ({dates}) for the site {site}.' => '',
    'Missing channel {channel} ({meter}) data for dates: {dates}.' => '@@{dates} חסרים נתונים עבור תאריכים: - {channel} ({meter})@@',
    'Report type' => '@@סוג דוח@@',
    'There are no sites to bill reports with active tenants or meter raw data.' => '@@אין אתרים לחיוב - אין דיירים פעילים או נתוני גלם.@@',
    'There is a {n} or more missing days during the report period.' => '@@ישנם {n} ימים של נתונים חסרים בתקופת הדוח@@',
    'Client' => 'לקוח',
    'DAT Export ' => 'DAT קובץ ייצוא',
    'Electric company NIS' => 'חברת חשמל ש"ח',
    'Electric company geva' => 'חברת חשמל גבע',
    'Electric company low rate' => 'חברת חשמל תעריף נמוך',
    'Electric company pisga' => 'חברת חשמל פסגה',
    'Electric company shefel' => 'חברת חשמל שפל',
    'Excel Export' => 'קובץ אקסל',
    'Fixed payment' => 'תשלום קבוע',
    'From date' => 'מתאריך',
    'Group usage percentage' => 'אחוז שימוש בקבוצה',
    'Missing channel {channel} ({meter}) data for dates: {dates}. Tenants: {tenants}' => '{tenants} דיירים:  .{dates} חסרים נתונים עבור תאריכים: - {channel} ({meter})',
    'Number of days with no data' => 'מספר ימים ללא נתונים',
    'PDF Export' => 'PDF קובץ',
    'Please set at least one export format.' => 'אנא בחר לפחות פורמט אחד של קובץ לייצוא',
    'Power factor' => 'מקדם הספק',
    'Published to client' => 'פורסם ללקוח',
    'Reports order of sorting' => 'סדר מיון נתונים בחשבונות',
    'Site' => 'אתר',
    'Tenants' => 'דיירים',
    'There are no rates available of tenant {name} for the period you selected.' => 'בטווח תאריכים אשר בחרת. {name} אין תעריפים זמינים עבור דייר',
    'There are no tenants with active rules for the site you selected.' => 'אין דיירים עם חוקים בתוקף עבור תקופה שבחרת.',
    'To date' => 'עד תאריך',
    'Total to pay based on Fixed load rules' => 'סה"כ לתשלום תוספות',
    'Total to pay based on Group load rules' => 'סה"כ לתשלום העמסות',
    'Total to pay based on Single rules' => 'סה"כ לתשלום לפי צריכת מונים',
    'Type' => 'סוג',
    'You are trying to issue report using COP calculation that requires at leat one Electric IsMain channel and at least one Air IsMain channel. Currently there are no Electric / Air channels marked IsMain to tenant {name}' => 'שגיאה: נסיון הפקת דוח תוך שימוש בשיטת חישוב COP ממונים ראשיים. חסר לפחות מונה ראשי אחד חשמל או מיזוג אויר. {name}',
    'You are trying to issue report with COP calculation of type No main air meter which requires at least one IsMain electrical channel.' => 'שגיאה: נסיון הפקת דוח תוך שימוש בשיטת חישוב COP בהעדר מונה מיזוג אויר ראשי. חסר לפחות מונה חשמל אחד ראשי.',
    'You are trying to issue report using Manual COP. Please make sure to enter the manual COP on Site.' => 'שגיאה: נסיון הפקת דוח תוך שימוש בשיטת חישוב COP ידני. אנא וודא להזין נתוני COP ברמת אתר.',
];
