<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Associated sites' => 'אתרים קשורים',
    'Associated tenants' => 'דיירים קשורים',
    'Associated users' => 'משתמשים קשורים',
    'Generate new password' => 'ייצר סיסמא חדשה',
    'Generate new username' => 'ייצר שם משתמש חדש',
    'Please fix the following errors for user {name}:' => ':{name} אנא תקן את השגיאות הבאות עבור משתמש ',
    'Status' => 'סטטוס',
    'Username' => 'שם משתמש',
    'Wrong username or password.' => 'שם משתמש או סיסמא לא נכונים',
    'Address' => 'כתובת',
    'Alert notification for Sites' => 'התראות עבור אתרים',
    'Alert notifications by Email' => 'משלוח התראות במייל',
    'Cell phone' => 'טלפון נייד',
    'Client' => 'לקוח',
    'Comment' => 'הערה',
    'Email' => 'מייל',
    'Fax' => 'פקס',
    'Job' => 'תפקיד',
    'Name' => 'שם מלא',
    'Password' => 'סיסמא',
    'Password repeat' => 'סיסמא שנית',
    'Phone' => 'טלפון',
    'Remember me' => 'זכור אותי',
    'Role' => 'הרשאה',
    'Site' => 'אתר',
    '{attribute} has already been taken.' => 'כבר תפוס {attribute}',
    '{attribute} is invalid.' => 'לא תקין {attribute}',
];
