<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Rate type' => '',
    'Tenant group' => '',
    '{attribute} percentage must be no greater than {value}.' => '',
    'Action' => 'פעולה',
    'Channel' => 'ערוץ',
    'Channel group' => 'קבוצת ערוצים',
    'Current multiplier' => 'מכפיל זרם',
    'Description' => 'תיאור',
    'From hour' => 'משעה',
    'Geva' => 'גבע',
    'Inactive channel can\'t be selected.' => 'לא ניתן לבחור ערוץ לא פעיל',
    'Meter ID' => 'מספר מונה',
    'Meter has been replaced' => 'מונה הוחלף',
    'Name' => 'שם',
    'Percent' => 'אחוז',
    'Pisga' => 'פסגה',
    'Relative to tenant\'s square footage must be greater than {min}.' => '{min}יחס צריכה לשטח הדייר צריך להיות גבוה מ',
    'Shefel' => 'שפל',
    'Start date' => 'תאריך תחילת תוקף',
    'Status' => 'סטטוס',
    'Tenant' => 'דייר',
    'This tenant has conflict rules with next tenants: {tenants}.' => '{tenants} דייר זה בקונפליקט עם הדיירים הבאים:',
    'To hour' => 'עד שעה',
    'Usage frequency' => 'תדירות שימוש',
    'Usage percentage' => 'אחוז שימוש',
    'Usage tenant group' => 'קבוצת דיירים לחישוב אחוז שימוש',
    'Usage type' => 'סוג שימוש',
    'Value' => 'ערך',
    'Voltage multiplier' => 'מכפיל מתח',
    '{attribute} has already been taken.' => 'כבר תפוס {attribute}',
    '{attribute} is required.' => 'שדה חובה {attribute}',
    '{attribute} must be greater than {value}.' => '{value}צריך להיות יותר גדול מ {attribute}',
];
