<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Direction' => 'כיוון',
    'AVG' => 'ממוצע',
    'Breaker name' => 'שם מפסק',
    'Channel' => 'ערוץ',
    'Channels' => 'ערוצים',
    'Communication type' => 'סוג תקשורת',
    'Current month' => 'חודש נוכחי',
    'Current multiplier' => 'מכפיל זרם',
    'Custom' => 'מותאם אישית',
    'Data usage method' => 'שיטת שימוש בנתונים',
    'End date' => 'תאריך סיום',
    'Export geva' => 'ייצוא גבע',
    'Export pisga' => 'ייצוא פסגה',
    'Export shefel' => 'ייצוא שפל',
    'From' => 'מתאריך',
    'Geva' => 'גבע',
    'Go back to issue bill' => 'חזרה להפקה',
    'Go to Channel raw data management' => 'ניהול נתוני גלם של ערוץ',
    'Last 2 months' => 'חודשיים אחרונים',
    'MODBUS' => 'MODBUS',
    'Max geva' => 'שיא ביקוש גבע',
    'Max pisga' => 'שיא ביקוש פסגה',
    'Max shefel' => 'שיא ביקוש שפל',
    'Meter ID' => 'מספר מונה',
    'Meter type has already been taken.' => 'מונה כבר תפוס',
    'Name' => 'שם סוג מונה',
    'Phases' => 'פאזות',
    'Phisical location on site' => 'מיקום באתר',
    'Pisga' => 'פסגה',
    'Reading date' => 'תאריך קריאה',
    'Readings for {date} must be set.' => '{date} חסרים נתונים עבור תאריך',
    'Shefel' => 'שפל',
    'Show data for period' => 'הצג נתונים עבור תקופה',
    'Site' => 'אתר',
    'Start date' => 'תאריך תחילת תוקף מונה',
    'Status' => 'סטטוס',
    'To' => 'עד תאריך',
    'Tree' => 'עץ מונים',
    'Type' => 'סוג',
    'Type category' => 'סוג מונה',
    'Voltage multiplier' => 'מכפיל מתח',
    '{attribute} for {date} must be a number.' => 'חייב להיות מספר {date} עבור {attribute}',
    '{attribute} for {date} must be no less than 0.' => 'חייב להיות גבוה מאפס {date} עבור {attribute}',
    'Is main' => 'ראשי',
];
