<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auto issue reports' => 'הגדרות הפקה אוטומטית',
    'IP' => '',
    'Address' => 'כתובת',
    'Cell phone' => 'טלפון נייד',
    'Client' => 'לקוח',
    'Comment' => 'הערה',
    'Comment for fixed addition' => 'הערה לתוספת כסף',
    'Day of billing' => 'יום הפקת חשבון',
    'Electric company ID' => 'מספר חוזה חברת חשמל',
    'Email' => 'מייל',
    'Fax' => 'פקס',
    'Fixed addition of' => 'העמסה ברמת אתר של',
    'Fixed payment' => 'תשלום קבוע',
    'Include VAT' => 'כלול מע"מ',
    'Job' => 'תפקיד',
    'Load as' => 'חשב כ',
    'Meter ID' => 'מספר מונה',
    'Name' => 'שם מלא',
    'Phone' => 'טלפון',
    'Rate type' => 'סוג תעריף',
    'To issue' => 'להפקה',
    'Value (money, kwh or percentage)' => 'ערך (סכום כסף, קוט"ש או אחוז)',
];
