<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Generate password and send email' => '',
    'Is create users' => '',
    'Show in DAT file' => '',
    'Accounting number' => 'מספר להנהלת חשבונות',
    'Address' => 'כתובת',
    'Billing content' => 'הערה לחשבון',
    'Cell phone' => 'טלפון נייד',
    'Comment' => 'הערה',
    'Email' => 'מייל',
    'Entrance date' => 'תאריך כניסה',
    'Exit date' => 'תאריך יציאה',
    'Fax' => 'פקס',
    'Fixed payment' => 'תשלום קבוע',
    'Hide drilldown on tenant bill' => 'אל תציג פירוט בחשבון לדייר',
    'ID with client' => 'מספר מזהה לקוח',
    'Included reports' => 'דוחות כלולים',
    'Job' => 'תפקיד',
    'Name' => 'שם מלא',
    'Phone' => 'טלפון',
    'Rate type' => 'סוג תעריף',
    'Site' => 'אתר',
    'Site fixed payment' => 'תשלום קבוע מרמת אתר',
    'Site rate type' => 'סוג תעריף מרמת אתר',
    'Square meters' => 'שטח במ"ר',
    'Tenants in group' => 'דיירים בקבוצה',
    'To issue' => 'להפקה',
    'Type' => 'סוג דייר',
    '{attribute} is invalid.' => 'לא תקין {attribute}',

    // Barcode settings
    'Barcode settings' => 'הגדרת ברקוד', // title
    'Prefix' => 'קידומת',
    'Ending' => "סיומת",
    'Client code' => 'קוד לקוח',
    'Contract id' => 'מספר חוזה',
    'Property id' => 'זיהוי הנכס',
    'Formatting' => 'פורמט'
];