<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Set {attribute} first on last record {link}' => '{link} ברשומה אחרונה של {attribute} קודם יש לקבוע',
    'This date period has already been taken by {link}' => '{link} תקופה זו כבר תפוסה ע"י',
    'VAT {name}' => '{name} מע"מ',
    '{attribute} must be no greater than {date}' => '{date}צריך להיות לא יותר גבוה מ {attribute}',
    '{attribute} must be no less than {date}' => '{date}צריך להיות לא יותר קטן מ {attribute}',
    'End date' => 'תאריך סיום',
    'Start date' => 'תאריך התחלה',
    'Vat' => 'מע"מ',
];
