<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Reset zoom' => '',
    'Reset zoom level 1:1' => '',
    'Administrator' => 'אדמין',
    'An internal server error occurred.' => 'שגיאת שרת פנימית',
    'Apr' => 'אפר',
    'April' => 'אפריל',
    'Are you sure?' => 'האם אתה בטוח?',
    'Aug' => 'אוג',
    'August' => 'אוגוסט',
    'Cancel' => 'בטל',
    'Client' => 'לקוח',
    'Close' => 'סגור',
    'Confirm' => 'אשר',
    'Dec' => 'דצמ',
    'December' => 'דצמבר',
    'English' => 'אנגלית',
    'Error' => 'שגיאה',
    'Feb' => 'פבר',
    'February' => 'פברואר',
    'First' => 'ראשון',
    'Fr' => 'שישי',
    'Fri' => 'שישי',
    'Friday' => 'שישי',
    'Guest' => 'אורח',
    'Hebrew' => 'עברית',
    'Invalid operator "{operator}".' => '"{operator}" אופרטור לא תקין',
    'Jan' => 'ינו',
    'January' => 'ינואר',
    'Jul' => 'יולי',
    'July' => 'יולי',
    'Jun' => 'יוני',
    'June' => 'יוני',
    'Last' => 'אחרון',
    'Mar' => 'מרץ',
    'March' => 'מרץ',
    'May' => 'מאי',
    'Mo' => 'שני',
    'Mon' => 'שני',
    'Monday' => 'שני',
    'NIS' => '₪',
    'Next' => 'הבא',
    'No' => 'נוב',
    'Nov' => 'נוב',
    'November' => 'נובמבר',
    'Oct' => 'אוק',
    'October' => 'אוקטובר',
    'Please fix the following errors:' => 'אנא תקן את השגיאות הבאות:',
    'Prev' => 'קודם',
    'Sa' => 'שבת',
    'Sat' => 'שבת',
    'Saturday' => 'שבת',
    'Sep' => 'ספט',
    'September' => 'ספטמבר',
    'Site' => 'אתר',
    'Su' => 'ראשון',
    'Sun' => 'ראשון',
    'Sunday' => 'ראשון',
    'Technician' => 'טכנאי',
    'Tenant' => 'דייר',
    'Th' => 'חמישי',
    'Thu' => 'חמישי',
    'Thursday' => 'חמישי',
    'Tu' => 'שלישי',
    'Tue' => 'שלישי',
    'Tuesday' => 'שלישי',
    'We' => 'רביעי',
    'Wed' => 'רביעי',
    'Wednesday' => 'רביעי',
    'Yes' => 'כן',
    'You must specify compareAttribute or compareValue' => 'עליך לספק נתון להשוואה',
    'number' => 'מספר',
    '{attribute} does not exist.' => 'לא קיים {attribute}',
    '{attribute} must be greater than "{compareValue}".' => '"{compareValue}"צריך להיות יותר גדול מ {attribute}',
    '{attribute} must be greater than or equal to "{compareValue}".' => '"{compareValue}"צריך להיות גדול או שווה ל {attribute}',
    '{attribute} must be less than "{compareValue}".' => '"{compareValue}"צריך להיות פחות מ {attribute}',
    '{attribute} must be less than or equal to "{compareValue}".' => '"{compareValue}"צריך להיות פחות או שווה ל {attribute}',
    '{attribute} must be repeated exactly.' => '{attribute} יש לחזור במדוייק על ',
    '{attribute} must not be equal to "{compareValue}".' => '{attribute} לא יכול להיות זהה ל {compareValue}',
];
