<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'High' => '',
    'Low' => '',
    'Rate to use for Power factor range' => 'תעריף לשימוש מקדם הספק',
    'Supreme' => '',
    'Active' => 'פעיל',
    'Basic rate in Agorot' => 'תעריף בסיס באגורות',
    'Created at' => 'נוצר ב',
    'Created by' => 'נוצר ע"י',
    'End date' => 'תאריך גמר תוקף',
    'Fall' => 'סתיו',
    'Fixed' => 'קבוע',
    'Fixed payment for monthly billed clients' => 'תשלום קבוע',
    'Geva' => 'גבע',
    'ID' => 'ID מספר מזהה',
    'Inactive' => 'לא פעיל',
    'Modified at' => 'שונה ב',
    'Modified by' => 'שונה ע"י',
    'Name' => 'שם',
    'Pisga' => 'פסגה',
    'Rate identifier' => 'סימול תעריף',
    'Season' => 'עונה',
    'Shefel' => 'שפל',
    'Spring' => 'אביב',
    'Start date' => 'תאריך תחילת תוקף',
    'Status' => 'סטטוס',
    'Summer' => 'קיץ',
    'TAOZ' => 'תעו"ז',
    'Type' => 'סוג',
    'Winter' => 'חורף',
];
