<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Flat percent' => 'אחוז ידני',
    '(V={v}, C={c})' => 'מתח={v}, זרם={c}',
    'Action' => 'פעולה',
    'Active' => 'פעיל',
    'By hour' => 'לפי שעה',
    'Channel' => 'ערוץ',
    'Channel group' => 'קבוצת ערוצים',
    'Created at' => 'נוצר ב',
    'Created by' => 'נוצר ע"י',
    'Description' => 'תיאור',
    'Flat % addition Total usage for this tenant.' => 'תוספת אחוז מצריכת הדייר',
    'Flat XX% addition from the total bill amount.' => 'תוספת אחוז מסך לתשלום',
    'From hour' => 'משעה',
    'Full' => 'מלא',
    'Geva' => 'גבע',
    'Group' => 'קבוצה',
    'Inactive' => 'לא פעיל',
    'Kwh' => 'קוט"ש',
    'Meter ID' => 'מספר מונה',
    'Meter has been replaced' => 'מונה הוחלף',
    'Modified at' => 'שונה ב',
    'Modified by' => 'שונה ע"י',
    'Money' => 'כסף',
    'Name' => 'שם',
    'One time' => 'חד פעמי',
    'Ongoing' => 'מתמשך',
    'Partial' => 'חלקי',
    'Percent' => 'אב',
    'Percentage' => 'אחוז',
    'Pisga' => 'פסגה',
    'Relative to tenant\'s footage' => 'לפי יחס שטחים',
    'Relative to tenant\'s square footage in relation to the site' => 'יחסי לשטח הדייר ביחד לשטח האתר',
    'Relative to tenant\'s usage' => 'לפי יחס צריכה',
    'Shefel' => 'שפל',
    'Single meter group load' => 'העמסת מונה בודד על קבוצה',
    'Single meter load' => 'העמסת מונה בודד',
    'Single tenant group load' => 'העמסת דייר על קבוצה',
    'Single tenant load' => 'העמסת דייר בודד',
    'Start date' => 'תאריך תחילת תוקף',
    'Status' => 'סטטוס',
    'Taken by {tenants}' => 'תפוס ע"י דיירים: {tenants}',
    'Tenant' => 'דייר',
    'Tenant group' => 'קבוצת דיירים',
    'Tenant name' => 'שם דייר',
    'To hour' => 'עד שעה',
    'Usage frequency' => 'תדירות שימוש',
    'Usage percentage' => 'שימוש באחוזים',
    'Usage tenant ID' => 'צריכת דייר ID',
    'Usage tenant group ID' => 'מזהה קבוצת דיירים להעמסת צריכה',
    'Usage type' => 'סוג שימוש',
    'Value' => 'ערך',
];
