<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Auto issue reports' => 'הגדרות הפקה אוטומטית',
    'IP' => '',
    'User' => '',
    'Active' => 'פעיל',
    'Address' => 'כתובת',
    'Cell phone' => 'טלפון נייד',
    'Client' => 'לקוח',
    'Client name' => 'שם לקוח',
    'Comment' => 'הערה',
    'Comment for fixed addition' => 'הערה לתוספת כסף',
    'Comments' => 'הערות',
    'Contact name' => 'שם איש קשר',
    'Created at' => 'נוצר ב',
    'Created by' => 'נוצר ע"י',
    'Date range to issue' => 'טווח תאריכים להפקה',
    'Day of billing' => 'יום הפקת חשבון',
    'Electric company ID' => 'מספר חוזה חברת חשמל',
    'Email' => 'מייל',
    'Fax' => 'פקס',
    'Fixed addition of' => 'העמסה ברמת אתר של',
    'Fixed payment' => 'תשלום קבוע',
    'Flat amount' => 'מספר',
    'Inactive' => 'לא פעיל',
    'Include VAT' => 'כלול מע"מ',
    'Include multipliers' => 'כלול מכפילים',
    'Job' => 'תפקיד',
    'Kwh' => 'קוט"ש',
    'Last issue date' => 'תאריך הפקה אחרון',
    'Load as' => 'חשב כ',
    'Modified at' => 'שונה ב',
    'Modified by' => 'שונה ע"י',
    'Money' => 'כסף',
    'Name' => 'שם מלא',
    'Not to issue' => 'לא להפקה',
    'Number of tenants to be issued' => 'מספר דיירים להפקה',
    'Old ID' => 'מזהה ישן',
    'Percentage' => 'אחוז',
    'Phone' => 'טלפון',
    'Rate type' => 'סוג תעריף',
    'Site' => 'אתר',
    'Site ID' => 'מזהה אתר ID',
    'Site name' => 'שם אתר',
    'Square meters' => 'שטח במ"ר',
    'Status' => 'סטטוס',
    'Value (money, kwh or percentage)' => 'ערך (סכום כסף, קוט"ש או אחוז)',
    'Yes, automatic' => 'כן, אוטומטי',
    'Yes, manual' => 'כן, ידני',
];
