<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Show in DAT file' => '',
    'User' => '',
    'Auto issue reports' => '@@@@',
    '(from site)' => '(מאתר)',
    'Accounting number' => 'מספר להנהלת חשבונות',
    'Active' => 'פעיל',
    'Address' => 'כתובת',
    'Billing content' => 'הערה לחשבון',
    'Cell phone' => 'טלפון נייד',
    'Client' => 'לקוח',
    'Client name' => 'שם לקוח',
    'Comment' => 'הערה',
    'Contact name' => 'שם איש קשר',
    'Created at' => 'נוצר ב',
    'Created by' => 'נוצר ע"י',
    'Email' => 'מייל',
    'Entrance date' => 'תאריך כניסה',
    'Exit date' => 'תאריך יציאה',
    'Fax' => 'פקס',
    'Fixed payment' => 'תשלום קבוע',
    'Hide drilldown on tenant bill' => 'אל תציג פירוט בחשבון לדייר',
    'ID with client' => 'מספר מזהה לקוח',
    'Inactive' => 'לא פעיל',
    'Included reports' => 'דוחות כלולים',
    'Job' => 'תפקיד',
    'Modified at' => 'שונה ב',
    'Modified by' => 'שונה ע"י',
    'Name' => 'שם מלא',
    'Old ID' => 'מזהה ישן',
    'Old channel ID' => 'מספר ערוץ ישן',
    'Phone' => 'טלפון',
    'Rate type' => 'סוג תעריף',
    'Report' => 'דוח',
    'Site' => 'אתר',
    'Site ID' => 'מזהה אתר ID',
    'Site footage' => 'שטח אתר',
    'Site name' => 'שם אתר',
    'Square meters' => 'מטר מרובע',
    'Status' => 'סטטוס',
    'Tenant' => 'דייר',
    'Tenant ID' => 'מזהה דייר ID',
    'Tenant group' => 'קבוצת דיירים',
    'Tenant name' => 'שם דייר',
    'Tenants in group' => 'דיירים בקבוצה',
    'To issue' => 'להפקה',
    'Transponder' => 'שנאי',
    'Type' => 'סוג',
];
