<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Is automatically generated' => 'נוצר אוטומטית',
    'Issued by' => 'נוצר ע"י',
    'TXT' => 'TXT',
    'The energy tree is empty for the site {name}.' => '{name} עץ האנרגיה ריק עבור אתר ',    
    'The total consumption of the first rule is negative for tenant {tenant} of site {site} between dates {dates}' =>'סך צריכה עבור דייר {tenant} הינו שלילי',
    'The total consumption is negative or equal to {n} for the site {site} during the report period ({dates}).' => ' {site} סך הצריכה שלילי או 0',
    'The total consumption of the sum of all first rules for a tenant {tenant} is negative for the site {site} during the report period ({dates}).' => '',
    'The energy tree is empty for this site.' => '@@עץ אנרגיה ריק עבור אתר זה@@',
    'The total consumption is negative or equal to {n}.' => '@@סך הצריכה 0 או שלילי@@',
    'The total consumption of the sum of all first rules for a tenant {name} is negative.' => '@@סך צריכה של סיכום כל החוקים מסוג ראשון עבור דייר זה היא 0@@',
    'Active' => 'פעיל',
    'Client' => 'לקוח',
    'Client name' => 'שם לקוח',
    'Created at' => 'נוצר ב',
    'Created by' => 'נוצר ע"י',
    'DAT' => 'DAT',
    'Energy report' => 'מאזן אנרגיה',
    'Excel' => 'אקסל',
    'File' => 'קובץ',
    'File type' => 'סוג קובץ',
    'From date' => 'מתאריך',
    'ID' => 'מספר מזהה ID',
    'Inactive' => 'לא פעיל',
    'Kwh report' => 'דוח קוט"ש',
    'Language' => 'שפה',
    'Level' => 'רמה',
    'Meters report' => 'דוח מונים',
    'Modified at' => 'שונה ב',
    'Modified by' => 'שונה ע"י',
    'NIS + Kwh report' => 'דוח שח + קוטש',
    'NIS report' => 'דוח שח',
    'PDF' => 'PDF',
    'Published to client' => 'פורסם ללקוח',
    'Rates comparison report' => 'דוח השוואת תעריפים',
    'Report' => 'דוח',
    'Site' => 'אתר',
    'Site name' => 'שם אתר',
    'Status' => 'סטטוס',
    'Summary report' => 'דוח מסכם',
    'Tenant' => 'דייר',
    'Tenant bills report' => 'חשבון לדייר',
    'To date' => 'עד תאריך',
    'Type' => 'סוג',
    'Yearly report' => 'דוח שנתי',
];
