<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'End date' => 'תאריך סיום',
    'Export' => 'ייצוא',
    'ID' => 'מזהה',
    'Import - Export' => 'ייבוא - ייצוא',
    'Meter channel ID' => 'מספר ערוץ מונה',
    'Parent meter channel ID' => 'מספר מונה אב',
    '{channel} ({subchannels})' => '',
    '485 line' => '485 קווי',
    'Active' => 'פעיל',
    'Breaker name' => 'שם מפסק',
    'Channel' => 'ערוץ',
    'Channel ID' => 'מספר ערוץ',
    'Channel group' => 'קבוצת ערוצים',
    'Channels' => 'ערוצים',
    'Communication type' => 'סוג תקשורת',
    'Created at' => 'נוצר ב',
    'Created by' => 'נוצר ע"י',
    'Current multiplier' => 'מכפיל זרם',
    'Data usage meter' => 'שיטת שימוש בנתונים',
    'Export geva' => 'ייצוא גבע',
    'Export pisga' => 'ייצוא פסגה',
    'Export shefel' => 'ייצוא שפל',
    'Geva' => 'גבע',
    'Import' => 'ייבוא',
    'Import + Export' => 'ייבוא + ייצוא',
    'Inactive' => 'לא פעיל',
    'KVAR geva' => 'KVAR גבע',
    'KVAR pisga' => 'KVAR פסגה',
    'KVAR shefel' => 'KVAR שפל',
    'Last 14 days' => '14 ימים אחרונים',
    'Last 60 days or up until season change' => '60 ימים אחרונים או עד שינוי עונה',
    'Last 60 days without seasons' => '60 ימים אחרונים ללא עונות',
    'MODBUS' => 'MODBUS',
    'Max geva' => 'שיא ביקוש גבע',
    'Max pisga' => 'שיא ביקוש פסגה',
    'Max shefel' => 'שיא ביקוש שפל',
    'Meter ID' => 'מספר מונה',
    'Meter type has already been taken.' => 'מונה כבר תפוס',
    'Modified at' => 'עודכן ב',
    'Modified by' => 'עודכן ע"י',
    'Name' => 'שם',
    'Not available' => 'לא זמין',
    'Old ID' => 'מזהה ישן',
    'PLC' => 'PLC',
    'Parent meter ID' => 'מזהה מונה אב',
    'Phases' => 'פאזות',
    'Phisical location on site' => 'מיקום באתר',
    'Pisga' => 'פסגה',
    'RF' => 'RF',
    'Reading date' => 'תאריך קריאה',
    'Reading geva' => 'קריאה גבע',
    'Reading pisga' => 'קריאה פסגה',
    'Reading shefel' => 'קריאה שפל',
    'Same period last year' => 'אותה תקופת אשתקד',
    'Serie Number' => 'מספר סדרה',
    'Shefel' => 'שפל',
    'Site' => 'אתר',
    'Site ID' => 'מזהה אתר',
    'Start date' => 'תאריך תחילת תוקף',
    'Status' => 'סטטוס',
    'Tenants' => 'דיירים',
    'Type' => 'סוג',
    'Voltage multiplier' => 'מכפיל מתח',
    '{name} - total {n, plural, =0{are no channels} =1{# channel} other{# channels}}' => '{n, plural, =0{אין ערוצים} =1{# ערוץ} other{# ערוצים}} - סה"כ - {name}',
];
