<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'User owner' => 'בעל המשתמש',
    'Username' => 'שם משתמש',
    'Active' => 'פעיל',
    'Address' => 'כתובת',
    'Alert notifications by Email' => 'התראות במייל',
    'Authorization key' => 'מפתח אישור',
    'Cell phone' => 'טלפון נייד',
    'Client' => 'לקוח',
    'Client name' => 'שם לקוח',
    'Comment' => 'הערה',
    'Contact name' => 'שם איש קשר',
    'Created at' => 'נוצר ב',
    'Created by' => 'נוצר ע"י',
    'Email' => 'מייל',
    'Fax' => 'פקס',
    'Inactive' => 'לא פעיל',
    'Job' => 'תפקיד',
    'Modified at' => 'שונה ב',
    'Modified by' => 'שונה ע"י',
    'Name' => 'שם',
    'Old ID' => 'מזהה ישן',
    'Password' => 'סיסמא',
    'Password reset token' => 'מפתח איפוס סיסמא',
    'Phone' => 'טלפון',
    'Role' => 'הרשאה',
    'Site' => 'אתר',
    'Status' => 'סטטוס',
    'User' => 'משתמש',
    'User ID' => 'מזהה משתמש ID',
];
