<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Automatically issued reports' => '',
    'Missing channel {channel} data' => '',
    'No new data were obtained from {name} during the latest 72 hours:' => 'לא התקבלו נתונים חדשים מאתר {name} במהלך 72 שעות אחרונות:',
    'helpdesk' => '',
    'Contact email' => 'מייל',
    'Contact name' => 'איש קשר',
    'Contact phone' => 'טלפון',
    'DAT' => 'DAT',
    'Daily alerts summary' => 'סיכום התראות יומי',
    'Date' => 'תאריך',
    'Description' => 'תיאור התראה',
    'Excel' => 'Excel',
    'From date' => 'מתאריך',
    'Hello, {name}' => '{name} שלום',
    'Link' => 'קישור',
    'New {link} have been created.' => 'קישור {link} חדש נוצר',
    'No new data were obtained from {name} during the latest 72 hours.' => 'לא התקבלו נתונים חדשים מאתר {name} במהלך 72 שעות אחרונות.',
    'PDF' => 'PDF',
    'Site' => 'אתר',
    'To date' => 'עד תאריך',
    'Type' => 'סוג',
    'Urgency' => 'דחיפות',
    'View' => 'צפייה',
];
