<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Total consumption for period {from} to {to}' => 'סה"כ צריכה עבור תקופה {from} עד {to}',
    'info@qlc.co.il' => '',
    'A' => 'A',
    'AVG' => 'ממוצע',
    'Calculate' => 'חשב',
    'Channel' => 'ערוץ',
    'Client' => 'לקוח',
    'Compare to same period before' => 'השווה לתקופה קודמת',
    'Current (A)' => 'זרם (A)',
    'Customer support' => 'לפניות ובירורים',
    'DAT' => 'DAT',
    'Daily' => 'יומי',
    'Date' => 'תאריך',
    'Drilldown' => 'פירוט',
    'Electricity' => 'חשמל',
    'Energy' => 'אנרגיה',
    'Excel' => 'אקסל',
    'Export to excel' => 'ייצוא לאקסל',
    'From date' => 'מתאריך',
    'Geva' => 'גבע',
    'Geva (old)' => 'גבע ישן',
    'Geva Kwh' => 'גבע Kwh',
    'Go back to {link}.' => '{link} חזרה ל',
    'History consumption' => 'הסטוריית צריכה',
    'KWH' => 'KWH',
    'Kvar' => 'Kvar',
    'Kvar (old)' => 'ישן Kvar',
    'Kvar/h' => 'Kvar/h',
    'Kwh' => 'Kwh',
    'Loading' => 'טוען...',
    'Logout' => 'יציאה',
    'Max demand' => 'שיא ביקוש',
    'Max demand (old)' => 'שיא ביקוש ישן',
    'Maximum {drilldown} drilldown is {n,plural,=0{# months} =1{# month} other{# months}}' => 'Maximum {drilldown} drilldown is {n,plural,=0{# months} =1{# month} other{# months}}',
    'Meter' => 'מונה',
    'Monthly' => 'חודשי',
    'No' => 'לא',
    'PDF' => 'PDF',
    'Phase' => 'פאזה',
    'Phone: 09-8911951. Fax: 09-8914555. Email: {link}' => 'טל: 09-8911951. פקס: 09-8914555. email: info@qlc.co.il',
    'Pisga' => 'פסגה',
    'Pisga (old)' => 'פסגה ישן',
    'Pisga Kwh' => 'פסגה Kwh',
    'Power (Pkw)' => 'הספק (Pkw)',
    'Power factor (Pf)' => 'מקדם הספק (Pf)',
    'R' => 'R',
    'RKWH' => 'RKWH',
    'Real time' => 'זמן אמת',
    'Real time consumption - Current (A)' => 'צריכה בזמן אמת - זרם (A)',
    'Real time consumption - Power (Pkw)' => 'צריכה בזמן אמת - הספק (Pkw)',
    'Reports' => 'דוחות',
    'S' => 'S',
    'Sderot HaDkalim, Industrial park, Kadima P.O.B 2550. Kadima 60920' => 'שד\' הדקלים אזור תעשייה קדימה. ת.ד. 2550. קדימה 60920',
    'Select an option' => 'בחר אפשרות',
    'Shefel' => 'שפל',
    'Shefel (old)' => 'שפל ישן',
    'Shefel Kwh' => 'שפל Kwh',
    'Sign In' => 'כניסה',
    'Site' => 'אתר',
    'Switch' => 'הצג',
    'T' => 'T',
    'TOTAL' => 'סה"כ',
    'Tenant' => 'דייר',
    'To date' => 'עד תאריך',
    'Total' => 'סה"כ',
    'V' => 'V',
    'Voltage (V)' => 'מתח (V)',
    'Yes' => 'כן',
    'homepage' => 'דף בית',
    '{name} - (V={v}, C={c})' => '{name} - (V={v}, C={c})',
    '{value} Kwh' => 'Kwh {value}',
];
